### ISSUE TITLE
Licence

### ISSUE THREAD

**Issue by tim3z** [cesarb/constant_time_eq#3]
Is there a licence available for this project/crate? Otherwise using it would probably be a huge copyright problem...

**Comment by cesarb** [comment]
It's on Cargo.toml, so it appears on the crates.io page:

`license = "CC0-1.0"`

**Comment by aep** [comment]
could you move to MIT+apache like the rest of rust? CC isn't well checked for compatibility.

**Comment by maxbrunsfeld** [comment]
I believe that legally, a license *name* like "CC0-1.0" is not a license. CC0-1.0 is a template for creating licenses. Including the name in the Cargo metadata is a helpful shorthand, but in order to actually license your work, you need to fill out the template and include a license file (named something like `LICENSE`) in your crate and in your repository.

When you get a chance, would you mind adding a license? It would allow others to use the project with less legal overhead.

**Comment by cesarb** [comment]
@maxbrunsfeld is commit 91f5db7556d089d6a43d19b4a804956edb140697 enough? In case it is, I'll tag a new release and push it to crates.io.

**Comment by maxbrunsfeld** [comment]
Yeah, I believe it is. Thanks!
