### ISSUE TITLE
Consider more robust strategy for constant time comparison (#[inline(never) is a hint)

### ISSUE THREAD

**Issue by ghost** [cesarb/constant_time_eq#5]
https://doc.rust-lang.org/reference/attributes/codegen.html#the-inline-attribute says that `#[inline(never)]` is a hint, and as such, *can* just be ignored by a compiler.

I've had a look around it seems like the only *correct* way to do constant time string comparison is to rely on a C library that somehow does it right, or use inline assembly in rust. Might not need to make the *whole* thing inline assembly, but at least a portion of it.

Also worth looking into is https://doc.dalek.rs/subtle/ . It looks to use inline asm as an optimization barrier, which is *probably* fine? Likely better than relying on `#[inline(never)]`, at least.

**Comment by cesarb** [comment]
Yes, the `#[inline(never)]` hint _can_ in theory be ignored by the compiler, but in practice, will it be ignored? (For instance, there are several places in the Linux kernel where it depends on `__attribute__((__noinline__))` being honored; since the Linux kernel can also be compiled through LLVM, it's unlikely that LLVM will one day decide to disregard this "hint".)

The correct way to do this is to either use [black_box](https://doc.rust-lang.org/core/hint/fn.black_box.html), or reimplement it yourself using inline assembly (the later probably being the most reliable option in theory if you are worried about `black_box` also being a "hint"; in practice, it will be implemented through the exact same empty inline assembly block). Unfortunately, neither `black_box` nor inline assembly are currently stable, so `#[inline(never)]` (or potentially unreliable volatile reads like the `subtle` crate does it) is the best thing which can currently be done in pure stable Rust. I'm waiting for stable inline assembly; as soon as it is available, I will make this crate use it instead of `#[inline(never)]`.

**Comment by oconnor663** [comment]
Stable inline assembly landed this week! :tada:

**Comment by cesarb** [comment]
I have just released version `0.2.0` of this crate, which uses inline assembly in the six architectures which have stable inline assembly (32-bit and 64-bit variants of x86, ARM, and RISC-V). For architectures which do not have stable inline assembly (like WASM), it still uses `#[inline(never)]`, but now combined with a volatile read (somewhat like what the `criterion` crate does for its `black_box` emulation). Unfortunately, this required increasing the minimum Rust version to the just released 1.59 (and it also introduces uses of `unsafe`, which some people dislike), so to prevent all users from breaking, I increased this crate's version from 0.1 to 0.2.

It would be possible to go further and implement the comparison itself in inline assembly or raw SIMD primitives, for a small speed gain (the autovectorization currently has to reduce all lanes to a single `u8`, since it cannot see that it's just going to be compared with 0) and a bit more certainty (a sufficiently evil optimizer could in theory stop the loop as soon as all bits of the accumulator are set, though that probably would be a pessimization). For now, I don't see that as being worth both the extra work and the extra risk of introducing a subtle bug in the comparison.
